
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: CertVault_development
test:
  <<: *default
  database: CertVault_test
production:
  <<: *default
  database: CertVault_production
  username: CertVault
  password: <%= ENV["CERTVAULT_DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
